apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-sample
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-sample
  template:
    metadata:
      labels:
        app: jenkins-sample
    spec:
      containers:
        - name: jenkins-sample
          image: docker.io/linjinbao666/jenkins-sample:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-sample
  namespace: default
spec:
  selector:
    app: jenkins-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
