apiVersion: v1
kind: Pod
metadata:
  name: kaniko-image-build
spec:
  restartPolicy: Never
  initContainers:
    - name: git-clone
      image: alpine/git
      args: ["clone", "--depth=1", "https://github.com/linjinbao666/python-bridge.git", "/workspace"]
      env:
        - name: HTTP_PROXY
          value: "http://192.168.1.104:10087"
        - name: HTTPS_PROXY
          value: "http://192.168.1.104:10087"
      volumeMounts:
        - name: workspace
          mountPath: /workspace
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        [
          "--dockerfile=Dockerfile",
          "--context=dir:///workspace",
          "--destination=docker.io/linjinbao666/jenkins-sample:latest",
          "--cleanup"
        ]
      env:
        - name: HTTP_PROXY
          value: "http://192.168.1.104:10087"
        - name: HTTPS_PROXY
          value: "http://192.168.1.104:10087"
        - name: NO_PROXY
          value: "localhost,127.0.0.1,.svc,.cluster.local"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
          readOnly: true
        - name: workspace
          mountPath: /workspace
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: workspace
      emptyDir: {}
